  INSERT INTO `teams` ( `name`, `icon`, `league` ) 
        VALUES 
                ("Arizona Diamondbacks","diamondbacks.png", 9),
                ("Atlanta Braves","braves.png", 9),
                ("Baltimore Orioles","orioles.png", 9),
                ("Boston Red Sox","red sox.png", 9),
                ("Chicago Cubs","cubs.png", 9),
                ("Chicago White Sox","white sox.png", 9),
                ("Cincinnati Reds","reds.png", 9),
                ("Cleveland Indians","indians.png", 9),
                ("Colorado Rockies","rockies.png", 9),
                ("Detroit Tigers","tigers.png", 9),
                ("Houston Astros","astros.png", 9),
                ("Kansas City Royals","royals.png", 9),
                ("Los Angeles Angels","angels.png", 9),
                ("Miami Marlins","marlins.png", 9),
                ("Milwaukee Brewers","brewers.png", 9),
                ("Minnesota Twins","twins.png", 9),
                ("New York Yankees","yankees.png", 9),
                ("Oakland Athletics","athletics.png", 9),
                ("Philadelphia Phillies","phillies.png", 9),
                ("Pittsburgh Pirates","pirates.png", 9),
                ("San Diego Padres","padres.png", 9),
                ("San Francisco Giants","giants.png", 9),
                ("Seattle Mariners","mariners.png", 9),
                ("St. Louis Cardinals","cardinals.png", 9),
                ("Tampa Bay Rays","rays.png", 9),
                ("Texas Rangers","rangers.png", 9),
                ("Toronto Blue Jays","blue jays.png", 9),
                ("Washington Nationals","nationals.png", 9)