
/* Insert test data into games table */
        INSERT INTO `games` ( `user`, `event`, `hometeam`,`awayteam`,`starttime` ) 
        VAlUES ( 1,1,'Dallas Stars','Toronto Maple Leafs', '7:00PM'),
         ( 1,1, 'New York Islanders', 'Calgary Flames',  '7:00PM'),
         ( 1,1, 'Columbus Blue Jackets', 'Vancouver Canucks',  '7:00PM'),
         ( 1,1, 'Ottawa Senators', 'Montreal Canadiens',  '7:00PM'),
         ( 1,0, 'New York Jets', 'New England Patriots',  '7:00PM'),
         ( 1,0, 'Buffalo Bills', 'New York Giants',  '11:00PM'),
         ( 1,0, 'Kansas City Chiefs', 'Green Bay Packers',  '7:00PM'),
         ( 1,2, 'Kansas City Chiefs', 'Green Bay Packers',  '7:00PM'),
         ( 1,3, 'Manchester United', 'Chelsea',  '7:00PM'),
         ( 1,3, 'Arsenal', 'Manchester City',  '7:00PM'),
         ( 1,3, 'West Ham United', 'Leicester City',  '7:00PM'),
         ( 1,4, 'Arsenal', 'Manchester City',  '7:00PM'),
         ( 1,4, 'West Ham United', 'Leicester City',  '7:00PM'),
         ( 1,5, 'Kansas City Chiefs', 'Green Bay Packers',  '7:00PM'),
         ( 1,5, 'Manchester United', 'Chelsea',  '7:00PM'),
         ( 1,5, 'Arsenal', 'Manchester City',  '7:00PM'),
         ( 1,5, 'West Ham United', 'Leicester City',  '7:00PM'),
         ( 1,5, 'Arsenal', 'Manchester City',  '7:00PM'),
         ( 1,5, 'West Ham United', 'Leicester City',  '7:00PM'),
         ( 1,3, 'Bournemouth', 'Burnley',  '4:00PM', '7:00PM'),
         ( 1,3, 'Southampton', 'Sheffield United', '7:00PM'),
         ( 1,3, 'Norwich City', 'Tottenham Hotspur',  '7:00PM'),
         ( 1,8, 'Philadelphia Eagles', 'Washington Redskins',  '3:30PM'),
         ( 1,16, 'Toronto Blue Jays', 'Boston Red Sox',  '3:30PM') ,
         ( 1,16, 'New York Yankees', 'Chicago White Sox',  '3:30PM'),
         ( 1,18, 'Los Angeles Clippers', 'Houston Rockets',  '3:30PM'),
         ( 1,18, 'Los Angeles Lakers', 'Boston Celtics',  '3:30PM'),
         ( 1,18, 'Oklahoma City Thunder', 'Denver Nuggets',  '3:30PM')
       