

INSERT INTO `teams` ( `name`, `icon`, `league` ) 
        VALUES 
                ("Anaheim Ducks","ducks.png", 6),
                ("Arizona Coyotes","coyotes.png", 6),
                ("Boston Bruins","bruins.png", 6),
                ("Buffalo Sabres","sabres.png", 6),
                ("Calgary Flames","flames.png", 6),
                ("Carolina Hurricanes","hurricanes.png", 6),
                ("Chicago Blackhawks","blackhawks.png", 6),
                ("Colorado Avalanche","avalanche.png", 6),
                ("Columbus Blue Jackets","blue jackets.png", 6),
                ("Dallas Stars","stars.png", 6),
                ("Detroit Red Wings","red wings.png", 6),
                ("Edmonton Oilers","oilers.png", 6),
                ("Florida Panthers","panthers.png", 6),
                ("Los Angeles Kings","kings.png", 6),
                ("Minnesota Wild","wild.png", 6),
                ("Montreal Canadiens","canadiens.png", 6),
                ("Nashville Predators","predators.png", 6),
                ("New Jersey Devils","devils.png", 6),
                ("New York Islanders","islanders.png", 6),
                ("New York Rangers","rangers.png", 6),
                ("Ottawa Senators","senators.png", 6),
                ("Philadelphia Flyers","flyers.png", 6),
                ("Pittsburgh Penguins","penguins.png", 6),
                ("San Jose Sharks","sharks.png", 6),
                ("St. Louis Blues","blues.png", 6),
                ("Tampa Bay Lightning","lightning.png", 6),
                ("Toronto Maple Leafs","maple leafs.png", 6),
                ("Vancouver Canucks","canucks.png", 6),
                ("Vegas Golden Knights","golden knights.png", 6),
                ("Washington Capitals","capitals.png", 6),
                ("Winnipeg Jets","jets.png", 6)